template: testify
template-data:
  boilerplate-file: ".mockery_boilerplate_text.txt"

dir: "{{.InterfaceDir}}/test_data"
filename: "mock_{{.InterfaceName | lower}}.go"
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "test_data"
force-file-write: false
formatter: goimports
log-level: info

packages:
  github.com/CantDefeatAirmanx/space-engeneering/order:
    config:
      all: false
      recursive: true
      include-interface-regex: ".*(Service|Repository|Client).*"
  
  github.com/CantDefeatAirmanx/space-engeneering/inventory:
    config:
      all: false
      recursive: true
      include-interface-regex: ".*(Service|Repository|Client).*"
  
  github.com/CantDefeatAirmanx/space-engeneering/payment:
    config:
      all: false
      recursive: true
      include-interface-regex: ".*(Service|Repository|Client).*"
