// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Code generated for CantDefeatAirmanx service
// © CantDefeatAirmanx 2025.

package mocks

import (
	"context"

	"github.com/CantDefeatAirmanx/space-engeneering/order/internal/client/payment/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentV1Client creates a new instance of MockPaymentV1Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentV1Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentV1Client {
	mock := &MockPaymentV1Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentV1Client is an autogenerated mock type for the PaymentV1Client type
type MockPaymentV1Client struct {
	mock.Mock
}

type MockPaymentV1Client_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentV1Client) EXPECT() *MockPaymentV1Client_Expecter {
	return &MockPaymentV1Client_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type MockPaymentV1Client
func (_mock *MockPaymentV1Client) PayOrder(ctx context.Context, params client_payment_v1.PayOrderParams) (*client_payment_v1.PayOrderResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 *client_payment_v1.PayOrderResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client_payment_v1.PayOrderParams) (*client_payment_v1.PayOrderResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client_payment_v1.PayOrderParams) *client_payment_v1.PayOrderResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client_payment_v1.PayOrderResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client_payment_v1.PayOrderParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentV1Client_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockPaymentV1Client_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - params client_payment_v1.PayOrderParams
func (_e *MockPaymentV1Client_Expecter) PayOrder(ctx interface{}, params interface{}) *MockPaymentV1Client_PayOrder_Call {
	return &MockPaymentV1Client_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, params)}
}

func (_c *MockPaymentV1Client_PayOrder_Call) Run(run func(ctx context.Context, params client_payment_v1.PayOrderParams)) *MockPaymentV1Client_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client_payment_v1.PayOrderParams
		if args[1] != nil {
			arg1 = args[1].(client_payment_v1.PayOrderParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentV1Client_PayOrder_Call) Return(payOrderResult *client_payment_v1.PayOrderResult, err error) *MockPaymentV1Client_PayOrder_Call {
	_c.Call.Return(payOrderResult, err)
	return _c
}

func (_c *MockPaymentV1Client_PayOrder_Call) RunAndReturn(run func(ctx context.Context, params client_payment_v1.PayOrderParams) (*client_payment_v1.PayOrderResult, error)) *MockPaymentV1Client_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
