services:
    postgres:
        image: postgres:15
        container_name: assembly-postgres
        ports:
            - 5433:5432
        env_file:
            - ./.env
        environment:
            - POSTGRES_USER=${postgres__user}
            - POSTGRES_PASSWORD=${postgres__password}
            - POSTGRES_DB=${postgres__dbName}
        volumes:
            - assembly-postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${postgres__user} -d ${postgres__dbName}']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        networks:
            - microservices-net
networks:
    microservices-net:
        external: true
volumes:
    assembly-postgres-data:
