// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: common/v1/notification_method.proto

package common_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NotificationMethod with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NotificationMethod) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NotificationMethod with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NotificationMethodMultiError, or nil if none found.
func (m *NotificationMethod) ValidateAll() error {
	return m.validate(true)
}

func (m *NotificationMethod) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ProviderName

	// no validation rules for Target

	if len(errors) > 0 {
		return NotificationMethodMultiError(errors)
	}

	return nil
}

// NotificationMethodMultiError is an error wrapping multiple validation errors
// returned by NotificationMethod.ValidateAll() if the designated constraints
// aren't met.
type NotificationMethodMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NotificationMethodMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NotificationMethodMultiError) AllErrors() []error { return m }

// NotificationMethodValidationError is the validation error returned by
// NotificationMethod.Validate if the designated constraints aren't met.
type NotificationMethodValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NotificationMethodValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NotificationMethodValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NotificationMethodValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NotificationMethodValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NotificationMethodValidationError) ErrorName() string {
	return "NotificationMethodValidationError"
}

// Error satisfies the builtin error interface
func (e NotificationMethodValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNotificationMethod.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NotificationMethodValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NotificationMethodValidationError{}
