// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/notification_method.proto

// Package common.v1 содержит общие типы данных

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationMethod описывает метод уведомления
type NotificationMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider_name имя провайдера (telegram, email, etc.)
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// target целевой идентификатор (chat_id:thread_id, email, etc.)
	Target        string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMethod) Reset() {
	*x = NotificationMethod{}
	mi := &file_common_v1_notification_method_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMethod) ProtoMessage() {}

func (x *NotificationMethod) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_notification_method_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMethod.ProtoReflect.Descriptor instead.
func (*NotificationMethod) Descriptor() ([]byte, []int) {
	return file_common_v1_notification_method_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationMethod) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *NotificationMethod) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_common_v1_notification_method_proto protoreflect.FileDescriptor

const file_common_v1_notification_method_proto_rawDesc = "" +
	"\n" +
	"#common/v1/notification_method.proto\x12\tcommon.v1\"Q\n" +
	"\x12NotificationMethod\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06targetBUZSgithub.com/CantDefeatAirmanx/space-engeneering/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_notification_method_proto_rawDescOnce sync.Once
	file_common_v1_notification_method_proto_rawDescData []byte
)

func file_common_v1_notification_method_proto_rawDescGZIP() []byte {
	file_common_v1_notification_method_proto_rawDescOnce.Do(func() {
		file_common_v1_notification_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_notification_method_proto_rawDesc), len(file_common_v1_notification_method_proto_rawDesc)))
	})
	return file_common_v1_notification_method_proto_rawDescData
}

var file_common_v1_notification_method_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_notification_method_proto_goTypes = []any{
	(*NotificationMethod)(nil), // 0: common.v1.NotificationMethod
}
var file_common_v1_notification_method_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_notification_method_proto_init() }
func file_common_v1_notification_method_proto_init() {
	if File_common_v1_notification_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_notification_method_proto_rawDesc), len(file_common_v1_notification_method_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_notification_method_proto_goTypes,
		DependencyIndexes: file_common_v1_notification_method_proto_depIdxs,
		MessageInfos:      file_common_v1_notification_method_proto_msgTypes,
	}.Build()
	File_common_v1_notification_method_proto = out.File
	file_common_v1_notification_method_proto_goTypes = nil
	file_common_v1_notification_method_proto_depIdxs = nil
}
