// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/payment_method.proto

// Package common.v1 содержит общие типы данных

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentMethod описывает метод оплаты
type PaymentMethod int32

const (
	// PAYMENT_METHOD_UNKNOWN_UNSPECIFIED неизвестный метод оплаты
	PaymentMethod_PAYMENT_METHOD_UNKNOWN_UNSPECIFIED PaymentMethod = 0
	// PAYMENT_METHOD_CARD оплата картой
	PaymentMethod_PAYMENT_METHOD_CARD PaymentMethod = 1
	// PAYMENT_METHOD_SPB оплата через СПБ
	PaymentMethod_PAYMENT_METHOD_SPB PaymentMethod = 2
	// PAYMENT_METHOD_CREDIT_CARD оплата кредитной картой
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD PaymentMethod = 3
	// PAYMENT_METHOD_INVESTOR_MONEY оплата инвестиционными деньгами
	PaymentMethod_PAYMENT_METHOD_INVESTOR_MONEY PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNKNOWN_UNSPECIFIED",
		1: "PAYMENT_METHOD_CARD",
		2: "PAYMENT_METHOD_SPB",
		3: "PAYMENT_METHOD_CREDIT_CARD",
		4: "PAYMENT_METHOD_INVESTOR_MONEY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNKNOWN_UNSPECIFIED": 0,
		"PAYMENT_METHOD_CARD":                1,
		"PAYMENT_METHOD_SPB":                 2,
		"PAYMENT_METHOD_CREDIT_CARD":         3,
		"PAYMENT_METHOD_INVESTOR_MONEY":      4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_payment_method_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_common_v1_payment_method_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_payment_method_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_payment_method_proto protoreflect.FileDescriptor

const file_common_v1_payment_method_proto_rawDesc = "" +
	"\n" +
	"\x1ecommon/v1/payment_method.proto\x12\tcommon.v1*\xab\x01\n" +
	"\rPaymentMethod\x12&\n" +
	"\"PAYMENT_METHOD_UNKNOWN_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PAYMENT_METHOD_CARD\x10\x01\x12\x16\n" +
	"\x12PAYMENT_METHOD_SPB\x10\x02\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x03\x12!\n" +
	"\x1dPAYMENT_METHOD_INVESTOR_MONEY\x10\x04BUZSgithub.com/CantDefeatAirmanx/space-engeneering/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_payment_method_proto_rawDescOnce sync.Once
	file_common_v1_payment_method_proto_rawDescData []byte
)

func file_common_v1_payment_method_proto_rawDescGZIP() []byte {
	file_common_v1_payment_method_proto_rawDescOnce.Do(func() {
		file_common_v1_payment_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_payment_method_proto_rawDesc), len(file_common_v1_payment_method_proto_rawDesc)))
	})
	return file_common_v1_payment_method_proto_rawDescData
}

var file_common_v1_payment_method_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_payment_method_proto_goTypes = []any{
	(PaymentMethod)(0), // 0: common.v1.PaymentMethod
}
var file_common_v1_payment_method_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_payment_method_proto_init() }
func file_common_v1_payment_method_proto_init() {
	if File_common_v1_payment_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_payment_method_proto_rawDesc), len(file_common_v1_payment_method_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_payment_method_proto_goTypes,
		DependencyIndexes: file_common_v1_payment_method_proto_depIdxs,
		EnumInfos:         file_common_v1_payment_method_proto_enumTypes,
	}.Build()
	File_common_v1_payment_method_proto = out.File
	file_common_v1_payment_method_proto_goTypes = nil
	file_common_v1_payment_method_proto_depIdxs = nil
}
