// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/user_info.proto

// Package common.v1 содержит общие типы данных

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserInfo описывает информацию о пользователе
type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// login логин пользователя
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	// email электронная почта пользователя
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// notification_methods метод уведомления
	NotificationMethods []*NotificationMethod `protobuf:"bytes,4,rep,name=notification_methods,json=notificationMethods,proto3" json:"notification_methods,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_common_v1_user_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_user_info_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetNotificationMethods() []*NotificationMethod {
	if x != nil {
		return x.NotificationMethods
	}
	return nil
}

var File_common_v1_user_info_proto protoreflect.FileDescriptor

const file_common_v1_user_info_proto_rawDesc = "" +
	"\n" +
	"\x19common/v1/user_info.proto\x12\tcommon.v1\x1a#common/v1/notification_method.proto\"\x88\x01\n" +
	"\bUserInfo\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12P\n" +
	"\x14notification_methods\x18\x04 \x03(\v2\x1d.common.v1.NotificationMethodR\x13notificationMethodsBUZSgithub.com/CantDefeatAirmanx/space-engeneering/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_user_info_proto_rawDescOnce sync.Once
	file_common_v1_user_info_proto_rawDescData []byte
)

func file_common_v1_user_info_proto_rawDescGZIP() []byte {
	file_common_v1_user_info_proto_rawDescOnce.Do(func() {
		file_common_v1_user_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_user_info_proto_rawDesc), len(file_common_v1_user_info_proto_rawDesc)))
	})
	return file_common_v1_user_info_proto_rawDescData
}

var file_common_v1_user_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_user_info_proto_goTypes = []any{
	(*UserInfo)(nil),           // 0: common.v1.UserInfo
	(*NotificationMethod)(nil), // 1: common.v1.NotificationMethod
}
var file_common_v1_user_info_proto_depIdxs = []int32{
	1, // 0: common.v1.UserInfo.notification_methods:type_name -> common.v1.NotificationMethod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_user_info_proto_init() }
func file_common_v1_user_info_proto_init() {
	if File_common_v1_user_info_proto != nil {
		return
	}
	file_common_v1_notification_method_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_user_info_proto_rawDesc), len(file_common_v1_user_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_user_info_proto_goTypes,
		DependencyIndexes: file_common_v1_user_info_proto_depIdxs,
		MessageInfos:      file_common_v1_user_info_proto_msgTypes,
	}.Build()
	File_common_v1_user_info_proto = out.File
	file_common_v1_user_info_proto_goTypes = nil
	file_common_v1_user_info_proto_depIdxs = nil
}
