// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: assembly/v1/assembly.proto

package assembly_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateAssemblyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAssemblyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAssemblyRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAssemblyRequestMultiError, or nil if none found.
func (m *CreateAssemblyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAssemblyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderUuid

	if len(errors) > 0 {
		return CreateAssemblyRequestMultiError(errors)
	}

	return nil
}

// CreateAssemblyRequestMultiError is an error wrapping multiple validation
// errors returned by CreateAssemblyRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateAssemblyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAssemblyRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAssemblyRequestMultiError) AllErrors() []error { return m }

// CreateAssemblyRequestValidationError is the validation error returned by
// CreateAssemblyRequest.Validate if the designated constraints aren't met.
type CreateAssemblyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAssemblyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAssemblyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAssemblyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAssemblyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAssemblyRequestValidationError) ErrorName() string {
	return "CreateAssemblyRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAssemblyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAssemblyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAssemblyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAssemblyRequestValidationError{}

// Validate checks the field values on CreateAssemblyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAssemblyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAssemblyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAssemblyResponseMultiError, or nil if none found.
func (m *CreateAssemblyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAssemblyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAssemblyInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateAssemblyResponseValidationError{
					field:  "AssemblyInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateAssemblyResponseValidationError{
					field:  "AssemblyInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAssemblyInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateAssemblyResponseValidationError{
				field:  "AssemblyInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateAssemblyResponseMultiError(errors)
	}

	return nil
}

// CreateAssemblyResponseMultiError is an error wrapping multiple validation
// errors returned by CreateAssemblyResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateAssemblyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAssemblyResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAssemblyResponseMultiError) AllErrors() []error { return m }

// CreateAssemblyResponseValidationError is the validation error returned by
// CreateAssemblyResponse.Validate if the designated constraints aren't met.
type CreateAssemblyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAssemblyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAssemblyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAssemblyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAssemblyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAssemblyResponseValidationError) ErrorName() string {
	return "CreateAssemblyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAssemblyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAssemblyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAssemblyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAssemblyResponseValidationError{}

// Validate checks the field values on SetAssemblyCompletedRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetAssemblyCompletedRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetAssemblyCompletedRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetAssemblyCompletedRequestMultiError, or nil if none found.
func (m *SetAssemblyCompletedRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetAssemblyCompletedRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderUuid

	// no validation rules for AssemblyUuid

	if len(errors) > 0 {
		return SetAssemblyCompletedRequestMultiError(errors)
	}

	return nil
}

// SetAssemblyCompletedRequestMultiError is an error wrapping multiple
// validation errors returned by SetAssemblyCompletedRequest.ValidateAll() if
// the designated constraints aren't met.
type SetAssemblyCompletedRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetAssemblyCompletedRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetAssemblyCompletedRequestMultiError) AllErrors() []error { return m }

// SetAssemblyCompletedRequestValidationError is the validation error returned
// by SetAssemblyCompletedRequest.Validate if the designated constraints
// aren't met.
type SetAssemblyCompletedRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetAssemblyCompletedRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetAssemblyCompletedRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetAssemblyCompletedRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetAssemblyCompletedRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetAssemblyCompletedRequestValidationError) ErrorName() string {
	return "SetAssemblyCompletedRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetAssemblyCompletedRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetAssemblyCompletedRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetAssemblyCompletedRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetAssemblyCompletedRequestValidationError{}

// Validate checks the field values on SetAssemblyCompletedResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetAssemblyCompletedResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetAssemblyCompletedResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetAssemblyCompletedResponseMultiError, or nil if none found.
func (m *SetAssemblyCompletedResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SetAssemblyCompletedResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AssemblyUuid

	if len(errors) > 0 {
		return SetAssemblyCompletedResponseMultiError(errors)
	}

	return nil
}

// SetAssemblyCompletedResponseMultiError is an error wrapping multiple
// validation errors returned by SetAssemblyCompletedResponse.ValidateAll() if
// the designated constraints aren't met.
type SetAssemblyCompletedResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetAssemblyCompletedResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetAssemblyCompletedResponseMultiError) AllErrors() []error { return m }

// SetAssemblyCompletedResponseValidationError is the validation error returned
// by SetAssemblyCompletedResponse.Validate if the designated constraints
// aren't met.
type SetAssemblyCompletedResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetAssemblyCompletedResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetAssemblyCompletedResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetAssemblyCompletedResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetAssemblyCompletedResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetAssemblyCompletedResponseValidationError) ErrorName() string {
	return "SetAssemblyCompletedResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SetAssemblyCompletedResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetAssemblyCompletedResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetAssemblyCompletedResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetAssemblyCompletedResponseValidationError{}

// Validate checks the field values on SetAssemblyStartedRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetAssemblyStartedRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetAssemblyStartedRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetAssemblyStartedRequestMultiError, or nil if none found.
func (m *SetAssemblyStartedRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetAssemblyStartedRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderUuid

	// no validation rules for AssemblyUuid

	if len(errors) > 0 {
		return SetAssemblyStartedRequestMultiError(errors)
	}

	return nil
}

// SetAssemblyStartedRequestMultiError is an error wrapping multiple validation
// errors returned by SetAssemblyStartedRequest.ValidateAll() if the
// designated constraints aren't met.
type SetAssemblyStartedRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetAssemblyStartedRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetAssemblyStartedRequestMultiError) AllErrors() []error { return m }

// SetAssemblyStartedRequestValidationError is the validation error returned by
// SetAssemblyStartedRequest.Validate if the designated constraints aren't met.
type SetAssemblyStartedRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetAssemblyStartedRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetAssemblyStartedRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetAssemblyStartedRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetAssemblyStartedRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetAssemblyStartedRequestValidationError) ErrorName() string {
	return "SetAssemblyStartedRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetAssemblyStartedRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetAssemblyStartedRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetAssemblyStartedRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetAssemblyStartedRequestValidationError{}

// Validate checks the field values on SetAssemblyStartedResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetAssemblyStartedResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetAssemblyStartedResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetAssemblyStartedResponseMultiError, or nil if none found.
func (m *SetAssemblyStartedResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SetAssemblyStartedResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AssemblyUuid

	if len(errors) > 0 {
		return SetAssemblyStartedResponseMultiError(errors)
	}

	return nil
}

// SetAssemblyStartedResponseMultiError is an error wrapping multiple
// validation errors returned by SetAssemblyStartedResponse.ValidateAll() if
// the designated constraints aren't met.
type SetAssemblyStartedResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetAssemblyStartedResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetAssemblyStartedResponseMultiError) AllErrors() []error { return m }

// SetAssemblyStartedResponseValidationError is the validation error returned
// by SetAssemblyStartedResponse.Validate if the designated constraints aren't met.
type SetAssemblyStartedResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetAssemblyStartedResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetAssemblyStartedResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetAssemblyStartedResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetAssemblyStartedResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetAssemblyStartedResponseValidationError) ErrorName() string {
	return "SetAssemblyStartedResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SetAssemblyStartedResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetAssemblyStartedResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetAssemblyStartedResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetAssemblyStartedResponseValidationError{}

// Validate checks the field values on GetAssemblyInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAssemblyInfoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAssemblyInfoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAssemblyInfoRequestMultiError, or nil if none found.
func (m *GetAssemblyInfoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAssemblyInfoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AssemblyUuid

	// no validation rules for OrderUuid

	if len(errors) > 0 {
		return GetAssemblyInfoRequestMultiError(errors)
	}

	return nil
}

// GetAssemblyInfoRequestMultiError is an error wrapping multiple validation
// errors returned by GetAssemblyInfoRequest.ValidateAll() if the designated
// constraints aren't met.
type GetAssemblyInfoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAssemblyInfoRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAssemblyInfoRequestMultiError) AllErrors() []error { return m }

// GetAssemblyInfoRequestValidationError is the validation error returned by
// GetAssemblyInfoRequest.Validate if the designated constraints aren't met.
type GetAssemblyInfoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAssemblyInfoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAssemblyInfoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAssemblyInfoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAssemblyInfoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAssemblyInfoRequestValidationError) ErrorName() string {
	return "GetAssemblyInfoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAssemblyInfoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAssemblyInfoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAssemblyInfoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAssemblyInfoRequestValidationError{}

// Validate checks the field values on GetAssemblyInfoResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAssemblyInfoResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAssemblyInfoResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAssemblyInfoResponseMultiError, or nil if none found.
func (m *GetAssemblyInfoResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAssemblyInfoResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAssemblyInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAssemblyInfoResponseValidationError{
					field:  "AssemblyInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAssemblyInfoResponseValidationError{
					field:  "AssemblyInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAssemblyInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAssemblyInfoResponseValidationError{
				field:  "AssemblyInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAssemblyInfoResponseMultiError(errors)
	}

	return nil
}

// GetAssemblyInfoResponseMultiError is an error wrapping multiple validation
// errors returned by GetAssemblyInfoResponse.ValidateAll() if the designated
// constraints aren't met.
type GetAssemblyInfoResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAssemblyInfoResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAssemblyInfoResponseMultiError) AllErrors() []error { return m }

// GetAssemblyInfoResponseValidationError is the validation error returned by
// GetAssemblyInfoResponse.Validate if the designated constraints aren't met.
type GetAssemblyInfoResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAssemblyInfoResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAssemblyInfoResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAssemblyInfoResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAssemblyInfoResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAssemblyInfoResponseValidationError) ErrorName() string {
	return "GetAssemblyInfoResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAssemblyInfoResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAssemblyInfoResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAssemblyInfoResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAssemblyInfoResponseValidationError{}

// Validate checks the field values on AssemblyInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AssemblyInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AssemblyInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AssemblyInfoMultiError, or
// nil if none found.
func (m *AssemblyInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *AssemblyInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AssemblyUuid

	// no validation rules for OrderUuid

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AssemblyInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AssemblyInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AssemblyInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AssemblyInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AssemblyInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AssemblyInfoValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AssemblyInfoMultiError(errors)
	}

	return nil
}

// AssemblyInfoMultiError is an error wrapping multiple validation errors
// returned by AssemblyInfo.ValidateAll() if the designated constraints aren't met.
type AssemblyInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AssemblyInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AssemblyInfoMultiError) AllErrors() []error { return m }

// AssemblyInfoValidationError is the validation error returned by
// AssemblyInfo.Validate if the designated constraints aren't met.
type AssemblyInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AssemblyInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AssemblyInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AssemblyInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AssemblyInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AssemblyInfoValidationError) ErrorName() string { return "AssemblyInfoValidationError" }

// Error satisfies the builtin error interface
func (e AssemblyInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAssemblyInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AssemblyInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AssemblyInfoValidationError{}
