// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: assembly/v1/assembly.proto

package assembly_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssemblyStatus статус сборки
type AssemblyStatus int32

const (
	// ASSEMBLY_STATUS_UNKNOWN статус сборки неизвестный
	AssemblyStatus_ASSEMBLY_STATUS_UNSPECIFIED AssemblyStatus = 0
	// ASSEMBLY_STATUS_NOT_STARTED статус сборки не начат
	AssemblyStatus_ASSEMBLY_STATUS_NOT_STARTED AssemblyStatus = 1
	// ASSEMBLY_STATUS_PENDING статус сборки в процессе
	AssemblyStatus_ASSEMBLY_STATUS_PENDING AssemblyStatus = 2
	// ASSEMBLY_STATUS_COMPLETED статус сборки завершен
	AssemblyStatus_ASSEMBLY_STATUS_COMPLETED AssemblyStatus = 3
)

// Enum value maps for AssemblyStatus.
var (
	AssemblyStatus_name = map[int32]string{
		0: "ASSEMBLY_STATUS_UNSPECIFIED",
		1: "ASSEMBLY_STATUS_NOT_STARTED",
		2: "ASSEMBLY_STATUS_PENDING",
		3: "ASSEMBLY_STATUS_COMPLETED",
	}
	AssemblyStatus_value = map[string]int32{
		"ASSEMBLY_STATUS_UNSPECIFIED": 0,
		"ASSEMBLY_STATUS_NOT_STARTED": 1,
		"ASSEMBLY_STATUS_PENDING":     2,
		"ASSEMBLY_STATUS_COMPLETED":   3,
	}
)

func (x AssemblyStatus) Enum() *AssemblyStatus {
	p := new(AssemblyStatus)
	*p = x
	return p
}

func (x AssemblyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssemblyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_assembly_v1_assembly_proto_enumTypes[0].Descriptor()
}

func (AssemblyStatus) Type() protoreflect.EnumType {
	return &file_assembly_v1_assembly_proto_enumTypes[0]
}

func (x AssemblyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssemblyStatus.Descriptor instead.
func (AssemblyStatus) EnumDescriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{0}
}

// CreateAssemblyRequest описывает запрос на создание сборки корабля
type CreateAssemblyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_uuid идентификатор заказа
	OrderUuid     string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssemblyRequest) Reset() {
	*x = CreateAssemblyRequest{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssemblyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssemblyRequest) ProtoMessage() {}

func (x *CreateAssemblyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssemblyRequest.ProtoReflect.Descriptor instead.
func (*CreateAssemblyRequest) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAssemblyRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

// CreateAssemblyResponse описывает ответ на запрос на создание сборки корабля
type CreateAssemblyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// assembly_uuid идентификатор сборки
	AssemblyInfo  *AssemblyInfo `protobuf:"bytes,1,opt,name=assembly_info,json=assemblyInfo,proto3" json:"assembly_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssemblyResponse) Reset() {
	*x = CreateAssemblyResponse{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssemblyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssemblyResponse) ProtoMessage() {}

func (x *CreateAssemblyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssemblyResponse.ProtoReflect.Descriptor instead.
func (*CreateAssemblyResponse) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAssemblyResponse) GetAssemblyInfo() *AssemblyInfo {
	if x != nil {
		return x.AssemblyInfo
	}
	return nil
}

// AssemblyCompletedRequest описывает запрос на завершение сборки корабля
type AssemblyCompletedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_uuid идентификатор заказа
	OrderUuid string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	// assembly_uuid идентификатор сборки
	AssemblyUuid  string `protobuf:"bytes,2,opt,name=assembly_uuid,json=assemblyUuid,proto3" json:"assembly_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssemblyCompletedRequest) Reset() {
	*x = AssemblyCompletedRequest{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyCompletedRequest) ProtoMessage() {}

func (x *AssemblyCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyCompletedRequest.ProtoReflect.Descriptor instead.
func (*AssemblyCompletedRequest) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{2}
}

func (x *AssemblyCompletedRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *AssemblyCompletedRequest) GetAssemblyUuid() string {
	if x != nil {
		return x.AssemblyUuid
	}
	return ""
}

// AssemblyCompletedResponse описывает ответ на запрос на завершение сборки корабля
type AssemblyCompletedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// assembly_uuid идентификатор сборки
	AssemblyUuid  string `protobuf:"bytes,1,opt,name=assembly_uuid,json=assemblyUuid,proto3" json:"assembly_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssemblyCompletedResponse) Reset() {
	*x = AssemblyCompletedResponse{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyCompletedResponse) ProtoMessage() {}

func (x *AssemblyCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyCompletedResponse.ProtoReflect.Descriptor instead.
func (*AssemblyCompletedResponse) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{3}
}

func (x *AssemblyCompletedResponse) GetAssemblyUuid() string {
	if x != nil {
		return x.AssemblyUuid
	}
	return ""
}

// AssemblyStartedRequest описывает запрос на начал сборки корабля
type AssemblyStartedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_uuid идентификатор заказа
	OrderUuid string `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	// assembly_uuid идентификатор сборки
	AssemblyUuid  string `protobuf:"bytes,2,opt,name=assembly_uuid,json=assemblyUuid,proto3" json:"assembly_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssemblyStartedRequest) Reset() {
	*x = AssemblyStartedRequest{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyStartedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyStartedRequest) ProtoMessage() {}

func (x *AssemblyStartedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyStartedRequest.ProtoReflect.Descriptor instead.
func (*AssemblyStartedRequest) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{4}
}

func (x *AssemblyStartedRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *AssemblyStartedRequest) GetAssemblyUuid() string {
	if x != nil {
		return x.AssemblyUuid
	}
	return ""
}

// AssemblyStartedResponse описывает ответ на запрос на начал сборки корабля
type AssemblyStartedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// assembly_uuid идентификатор сборки
	AssemblyUuid  string `protobuf:"bytes,1,opt,name=assembly_uuid,json=assemblyUuid,proto3" json:"assembly_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssemblyStartedResponse) Reset() {
	*x = AssemblyStartedResponse{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyStartedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyStartedResponse) ProtoMessage() {}

func (x *AssemblyStartedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyStartedResponse.ProtoReflect.Descriptor instead.
func (*AssemblyStartedResponse) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{5}
}

func (x *AssemblyStartedResponse) GetAssemblyUuid() string {
	if x != nil {
		return x.AssemblyUuid
	}
	return ""
}

// GetAssemblyInfoRequest описывает запрос на получение информации о сборке корабля
type GetAssemblyInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// assembly_uuid идентификатор сборки
	AssemblyUuid string `protobuf:"bytes,1,opt,name=assembly_uuid,json=assemblyUuid,proto3" json:"assembly_uuid,omitempty"`
	// order_uuid идентификатор заказа
	OrderUuid     string `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssemblyInfoRequest) Reset() {
	*x = GetAssemblyInfoRequest{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssemblyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssemblyInfoRequest) ProtoMessage() {}

func (x *GetAssemblyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssemblyInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAssemblyInfoRequest) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{6}
}

func (x *GetAssemblyInfoRequest) GetAssemblyUuid() string {
	if x != nil {
		return x.AssemblyUuid
	}
	return ""
}

func (x *GetAssemblyInfoRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

// GetAssemblyInfoResponse описывает ответ на запрос на получение информации о сборке корабля
type GetAssemblyInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// assembly_info информация о сборке корабля
	AssemblyInfo  *AssemblyInfo `protobuf:"bytes,1,opt,name=assembly_info,json=assemblyInfo,proto3" json:"assembly_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssemblyInfoResponse) Reset() {
	*x = GetAssemblyInfoResponse{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssemblyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssemblyInfoResponse) ProtoMessage() {}

func (x *GetAssemblyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssemblyInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAssemblyInfoResponse) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssemblyInfoResponse) GetAssemblyInfo() *AssemblyInfo {
	if x != nil {
		return x.AssemblyInfo
	}
	return nil
}

// AssemblyInfo описывает информацию о сборке корабля
type AssemblyInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// assembly_uuid идентификатор сборки
	AssemblyUuid string `protobuf:"bytes,1,opt,name=assembly_uuid,json=assemblyUuid,proto3" json:"assembly_uuid,omitempty"`
	// order_uuid идентификатор заказа
	OrderUuid string `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	// status статус сборки
	Status AssemblyStatus `protobuf:"varint,3,opt,name=status,proto3,enum=assembly.v1.AssemblyStatus" json:"status,omitempty"`
	// created_at дата создания
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at дата обновления
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssemblyInfo) Reset() {
	*x = AssemblyInfo{}
	mi := &file_assembly_v1_assembly_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyInfo) ProtoMessage() {}

func (x *AssemblyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_assembly_v1_assembly_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyInfo.ProtoReflect.Descriptor instead.
func (*AssemblyInfo) Descriptor() ([]byte, []int) {
	return file_assembly_v1_assembly_proto_rawDescGZIP(), []int{8}
}

func (x *AssemblyInfo) GetAssemblyUuid() string {
	if x != nil {
		return x.AssemblyUuid
	}
	return ""
}

func (x *AssemblyInfo) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *AssemblyInfo) GetStatus() AssemblyStatus {
	if x != nil {
		return x.Status
	}
	return AssemblyStatus_ASSEMBLY_STATUS_UNSPECIFIED
}

func (x *AssemblyInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AssemblyInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_assembly_v1_assembly_proto protoreflect.FileDescriptor

const file_assembly_v1_assembly_proto_rawDesc = "" +
	"\n" +
	"\x1aassembly/v1/assembly.proto\x12\vassembly.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n" +
	"\x15CreateAssemblyRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\"X\n" +
	"\x16CreateAssemblyResponse\x12>\n" +
	"\rassembly_info\x18\x01 \x01(\v2\x19.assembly.v1.AssemblyInfoR\fassemblyInfo\"^\n" +
	"\x18AssemblyCompletedRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12#\n" +
	"\rassembly_uuid\x18\x02 \x01(\tR\fassemblyUuid\"@\n" +
	"\x19AssemblyCompletedResponse\x12#\n" +
	"\rassembly_uuid\x18\x01 \x01(\tR\fassemblyUuid\"\\\n" +
	"\x16AssemblyStartedRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12#\n" +
	"\rassembly_uuid\x18\x02 \x01(\tR\fassemblyUuid\">\n" +
	"\x17AssemblyStartedResponse\x12#\n" +
	"\rassembly_uuid\x18\x01 \x01(\tR\fassemblyUuid\"\\\n" +
	"\x16GetAssemblyInfoRequest\x12#\n" +
	"\rassembly_uuid\x18\x01 \x01(\tR\fassemblyUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\"Y\n" +
	"\x17GetAssemblyInfoResponse\x12>\n" +
	"\rassembly_info\x18\x01 \x01(\v2\x19.assembly.v1.AssemblyInfoR\fassemblyInfo\"\xfd\x01\n" +
	"\fAssemblyInfo\x12#\n" +
	"\rassembly_uuid\x18\x01 \x01(\tR\fassemblyUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.assembly.v1.AssemblyStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x8e\x01\n" +
	"\x0eAssemblyStatus\x12\x1f\n" +
	"\x1bASSEMBLY_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bASSEMBLY_STATUS_NOT_STARTED\x10\x01\x12\x1b\n" +
	"\x17ASSEMBLY_STATUS_PENDING\x10\x02\x12\x1d\n" +
	"\x19ASSEMBLY_STATUS_COMPLETED\x10\x032\x8c\x03\n" +
	"\x0fAssemblyService\x12Y\n" +
	"\x0eCreateAssembly\x12\".assembly.v1.CreateAssemblyRequest\x1a#.assembly.v1.CreateAssemblyResponse\x12b\n" +
	"\x11AssemblyCompleted\x12%.assembly.v1.AssemblyCompletedRequest\x1a&.assembly.v1.AssemblyCompletedResponse\x12\\\n" +
	"\x0fAssemblyStarted\x12#.assembly.v1.AssemblyStartedRequest\x1a$.assembly.v1.AssemblyStartedResponse\x12\\\n" +
	"\x0fGetAssemblyInfo\x12#.assembly.v1.GetAssemblyInfoRequest\x1a$.assembly.v1.GetAssemblyInfoResponseBUZSgithub.com/CantDefeatAirmanx/space-engeneering/shared/proto/assembly/v1;assembly_v1b\x06proto3"

var (
	file_assembly_v1_assembly_proto_rawDescOnce sync.Once
	file_assembly_v1_assembly_proto_rawDescData []byte
)

func file_assembly_v1_assembly_proto_rawDescGZIP() []byte {
	file_assembly_v1_assembly_proto_rawDescOnce.Do(func() {
		file_assembly_v1_assembly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assembly_v1_assembly_proto_rawDesc), len(file_assembly_v1_assembly_proto_rawDesc)))
	})
	return file_assembly_v1_assembly_proto_rawDescData
}

var file_assembly_v1_assembly_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_assembly_v1_assembly_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_assembly_v1_assembly_proto_goTypes = []any{
	(AssemblyStatus)(0),               // 0: assembly.v1.AssemblyStatus
	(*CreateAssemblyRequest)(nil),     // 1: assembly.v1.CreateAssemblyRequest
	(*CreateAssemblyResponse)(nil),    // 2: assembly.v1.CreateAssemblyResponse
	(*AssemblyCompletedRequest)(nil),  // 3: assembly.v1.AssemblyCompletedRequest
	(*AssemblyCompletedResponse)(nil), // 4: assembly.v1.AssemblyCompletedResponse
	(*AssemblyStartedRequest)(nil),    // 5: assembly.v1.AssemblyStartedRequest
	(*AssemblyStartedResponse)(nil),   // 6: assembly.v1.AssemblyStartedResponse
	(*GetAssemblyInfoRequest)(nil),    // 7: assembly.v1.GetAssemblyInfoRequest
	(*GetAssemblyInfoResponse)(nil),   // 8: assembly.v1.GetAssemblyInfoResponse
	(*AssemblyInfo)(nil),              // 9: assembly.v1.AssemblyInfo
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
}
var file_assembly_v1_assembly_proto_depIdxs = []int32{
	9,  // 0: assembly.v1.CreateAssemblyResponse.assembly_info:type_name -> assembly.v1.AssemblyInfo
	9,  // 1: assembly.v1.GetAssemblyInfoResponse.assembly_info:type_name -> assembly.v1.AssemblyInfo
	0,  // 2: assembly.v1.AssemblyInfo.status:type_name -> assembly.v1.AssemblyStatus
	10, // 3: assembly.v1.AssemblyInfo.created_at:type_name -> google.protobuf.Timestamp
	10, // 4: assembly.v1.AssemblyInfo.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: assembly.v1.AssemblyService.CreateAssembly:input_type -> assembly.v1.CreateAssemblyRequest
	3,  // 6: assembly.v1.AssemblyService.AssemblyCompleted:input_type -> assembly.v1.AssemblyCompletedRequest
	5,  // 7: assembly.v1.AssemblyService.AssemblyStarted:input_type -> assembly.v1.AssemblyStartedRequest
	7,  // 8: assembly.v1.AssemblyService.GetAssemblyInfo:input_type -> assembly.v1.GetAssemblyInfoRequest
	2,  // 9: assembly.v1.AssemblyService.CreateAssembly:output_type -> assembly.v1.CreateAssemblyResponse
	4,  // 10: assembly.v1.AssemblyService.AssemblyCompleted:output_type -> assembly.v1.AssemblyCompletedResponse
	6,  // 11: assembly.v1.AssemblyService.AssemblyStarted:output_type -> assembly.v1.AssemblyStartedResponse
	8,  // 12: assembly.v1.AssemblyService.GetAssemblyInfo:output_type -> assembly.v1.GetAssemblyInfoResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_assembly_v1_assembly_proto_init() }
func file_assembly_v1_assembly_proto_init() {
	if File_assembly_v1_assembly_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assembly_v1_assembly_proto_rawDesc), len(file_assembly_v1_assembly_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assembly_v1_assembly_proto_goTypes,
		DependencyIndexes: file_assembly_v1_assembly_proto_depIdxs,
		EnumInfos:         file_assembly_v1_assembly_proto_enumTypes,
		MessageInfos:      file_assembly_v1_assembly_proto_msgTypes,
	}.Build()
	File_assembly_v1_assembly_proto = out.File
	file_assembly_v1_assembly_proto_goTypes = nil
	file_assembly_v1_assembly_proto_depIdxs = nil
}
