services:
    mongodb:
        image: mongo:7.0.5
        container_name: inventory-mongodb
        ports:
            - ${mongo__port}:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${mongo__username}
            - MONGO_INITDB_ROOT_PASSWORD=${mongo__password}
        env_file:
            - ./.env
        volumes:
            - mongo-data:/data/db
        healthcheck:
            test: [
                    'CMD-SHELL',
                    "echo 'db.runCommand({ ping: 1 }).ok' | \
                    mongosh --quiet \
                    -u ${mongo__username} \
                    -p ${mongo__password} \
                    --authenticationDatabase ${mongo__authSource}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        networks:
            - microservices-net
networks:
    microservices-net:
        external: true
volumes:
    mongo-data:
