services:
    mongodb:
        image: mongo:7.0.5
        container_name: inventory-mongodb
        ports:
            - ${MONGO_PORT}:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        env_file:
            - ../../inventory/.env
        volumes:
            - mongo-data:/data/db
        healthcheck:
            test: [
                    'CMD-SHELL',
                    "echo 'db.runCommand({ ping: 1 }).ok' | \
                    mongosh --quiet \
                    -u ${MONGO_USERNAME} \
                    -p ${MONGO_PASSWORD} \
                    --authenticationDatabase ${MONGO_AUTH_SOURCE}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        networks:
            - microservices-net
networks:
    microservices-net:
        external: true
volumes:
    mongo-data:
