// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: user/v1/user.proto

// Package user.v1 содержит API для работы с пользователем

package user_v1

import (
	v1 "github.com/CantDefeatAirmanx/space-engeneering/shared/pkg/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest описывает запрос на регистрацию пользователя
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// info информация о пользователе
	Info *RegisterUserInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// email электронная почта пользователя
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// password пароль пользователя
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetInfo() *RegisterUserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegisterUserInfo описывает информацию о пользователе необходимую для регистрации
type RegisterUserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// login логин пользователя
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// email электронная почта пользователя
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// notification_methods метод уведомления
	NotificationMethods []*v1.NotificationMethod `protobuf:"bytes,3,rep,name=notification_methods,json=notificationMethods,proto3" json:"notification_methods,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterUserInfo) Reset() {
	*x = RegisterUserInfo{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserInfo) ProtoMessage() {}

func (x *RegisterUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserInfo.ProtoReflect.Descriptor instead.
func (*RegisterUserInfo) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserInfo) GetNotificationMethods() []*v1.NotificationMethod {
	if x != nil {
		return x.NotificationMethods
	}
	return nil
}

// RegisterResponse описывает ответ на запрос на регистрацию пользователя
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_uuid идентификатор пользователя
	UserUuid      string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// GetUserRequest описывает запрос на получение информации о пользователе
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user_uuid идентификатор пользователя
	UserUuid      string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// GetUserResponse описывает ответ на запрос на получение информации о пользователе
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user информация о пользователе
	User          *v1.UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserResponse) GetUser() *v1.UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x19common/v1/user_info.proto\x1a#common/v1/notification_method.proto\"r\n" +
	"\x0fRegisterRequest\x12-\n" +
	"\x04info\x18\x01 \x01(\v2\x19.user.v1.RegisterUserInfoR\x04info\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x90\x01\n" +
	"\x10RegisterUserInfo\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12P\n" +
	"\x14notification_methods\x18\x03 \x03(\v2\x1d.common.v1.NotificationMethodR\x13notificationMethods\"/\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"-\n" +
	"\x0eGetUserRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\":\n" +
	"\x0fGetUserResponse\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.common.v1.UserInfoR\x04user2\x8c\x01\n" +
	"\vUserService\x12?\n" +
	"\bRegister\x12\x18.user.v1.RegisterRequest\x1a\x19.user.v1.RegisterResponse\x12<\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponseBMZKgithub.com/CantDefeatAirmanx/space-engeneering/shared/proto/user/v1;user_v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_v1_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: user.v1.RegisterRequest
	(*RegisterUserInfo)(nil),      // 1: user.v1.RegisterUserInfo
	(*RegisterResponse)(nil),      // 2: user.v1.RegisterResponse
	(*GetUserRequest)(nil),        // 3: user.v1.GetUserRequest
	(*GetUserResponse)(nil),       // 4: user.v1.GetUserResponse
	(*v1.NotificationMethod)(nil), // 5: common.v1.NotificationMethod
	(*v1.UserInfo)(nil),           // 6: common.v1.UserInfo
}
var file_user_v1_user_proto_depIdxs = []int32{
	1, // 0: user.v1.RegisterRequest.info:type_name -> user.v1.RegisterUserInfo
	5, // 1: user.v1.RegisterUserInfo.notification_methods:type_name -> common.v1.NotificationMethod
	6, // 2: user.v1.GetUserResponse.user:type_name -> common.v1.UserInfo
	0, // 3: user.v1.UserService.Register:input_type -> user.v1.RegisterRequest
	3, // 4: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	2, // 5: user.v1.UserService.Register:output_type -> user.v1.RegisterResponse
	4, // 6: user.v1.UserService.GetUser:output_type -> user.v1.GetUserResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
