// Code generated by ogen, DO NOT EDIT.
package order_v1

type CancelOrderRes interface {
	cancelOrderRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type DeleteOrderRes interface {
	deleteOrderRes()
}

type GetOrderRes interface {
	getOrderRes()
}

type PayOrderRes interface {
	payOrderRes()
}
