// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements cancelOrder operation.
	//
	// Cancel an order by UUID.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrder implements createOrder operation.
	//
	// Create a new order.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequestBody) (CreateOrderRes, error)
	// DeleteOrder implements deleteOrder operation.
	//
	// Delete an order by UUID.
	//
	// DELETE /api/v1/orders/{order_uuid}
	DeleteOrder(ctx context.Context, params DeleteOrderParams) (DeleteOrderRes, error)
	// GetOrder implements getOrder operation.
	//
	// Get an order by UUID.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrder(ctx context.Context, params GetOrderParams) (GetOrderRes, error)
	// PayOrder implements payOrder operation.
	//
	// Pay an order by UUID.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequestBody, params PayOrderParams) (PayOrderRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
