// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: events/ship/v1/ship.proto

package ship_events_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common_v1 "github.com/CantDefeatAirmanx/space-engeneering/shared/pkg/proto/common/v1"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common_v1.PaymentMethod(0)
)

// Validate checks the field values on ShipAssembledEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ShipAssembledEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShipAssembledEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ShipAssembledEventMultiError, or nil if none found.
func (m *ShipAssembledEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *ShipAssembledEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for EventUuid

	// no validation rules for OrderUuid

	// no validation rules for UserUuid

	// no validation rules for PaymentMethod

	if len(errors) > 0 {
		return ShipAssembledEventMultiError(errors)
	}

	return nil
}

// ShipAssembledEventMultiError is an error wrapping multiple validation errors
// returned by ShipAssembledEvent.ValidateAll() if the designated constraints
// aren't met.
type ShipAssembledEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShipAssembledEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShipAssembledEventMultiError) AllErrors() []error { return m }

// ShipAssembledEventValidationError is the validation error returned by
// ShipAssembledEvent.Validate if the designated constraints aren't met.
type ShipAssembledEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShipAssembledEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShipAssembledEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShipAssembledEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShipAssembledEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShipAssembledEventValidationError) ErrorName() string {
	return "ShipAssembledEventValidationError"
}

// Error satisfies the builtin error interface
func (e ShipAssembledEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShipAssembledEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShipAssembledEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShipAssembledEventValidationError{}
