// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: events/order/v1/order.proto

package order_events_v1

import (
	v1 "github.com/CantDefeatAirmanx/space-engeneering/shared/pkg/proto/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderEventType тип события заказа
type OrderEventType int32

const (
	// ORDER_EVENT_TYPE_UNSPECIFIED неизвестный тип события
	OrderEventType_ORDER_EVENT_TYPE_UNSPECIFIED OrderEventType = 0
	// ORDER_EVENT_TYPE_PAID тип события оплаты заказа
	OrderEventType_ORDER_EVENT_TYPE_PAID OrderEventType = 1
)

// Enum value maps for OrderEventType.
var (
	OrderEventType_name = map[int32]string{
		0: "ORDER_EVENT_TYPE_UNSPECIFIED",
		1: "ORDER_EVENT_TYPE_PAID",
	}
	OrderEventType_value = map[string]int32{
		"ORDER_EVENT_TYPE_UNSPECIFIED": 0,
		"ORDER_EVENT_TYPE_PAID":        1,
	}
)

func (x OrderEventType) Enum() *OrderEventType {
	p := new(OrderEventType)
	*p = x
	return p
}

func (x OrderEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_order_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderEventType) Type() protoreflect.EnumType {
	return &file_events_order_v1_order_proto_enumTypes[0]
}

func (x OrderEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderEventType.Descriptor instead.
func (OrderEventType) EnumDescriptor() ([]byte, []int) {
	return file_events_order_v1_order_proto_rawDescGZIP(), []int{0}
}

// OrderEventEnvelope описывает обертку для события заказа
type OrderEventEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_type тип события
	EventType OrderEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=events.order.v1.OrderEventType" json:"event_type,omitempty"`
	// event_uuid идентификатор события
	EventUuid string `protobuf:"bytes,2,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`
	// event событие
	//
	// Types that are valid to be assigned to Event:
	//
	//	*OrderEventEnvelope_OrderPaid
	Event         isOrderEventEnvelope_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderEventEnvelope) Reset() {
	*x = OrderEventEnvelope{}
	mi := &file_events_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderEventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderEventEnvelope) ProtoMessage() {}

func (x *OrderEventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_events_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderEventEnvelope.ProtoReflect.Descriptor instead.
func (*OrderEventEnvelope) Descriptor() ([]byte, []int) {
	return file_events_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderEventEnvelope) GetEventType() OrderEventType {
	if x != nil {
		return x.EventType
	}
	return OrderEventType_ORDER_EVENT_TYPE_UNSPECIFIED
}

func (x *OrderEventEnvelope) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *OrderEventEnvelope) GetEvent() isOrderEventEnvelope_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *OrderEventEnvelope) GetOrderPaid() *OrderPaidEvent {
	if x != nil {
		if x, ok := x.Event.(*OrderEventEnvelope_OrderPaid); ok {
			return x.OrderPaid
		}
	}
	return nil
}

type isOrderEventEnvelope_Event interface {
	isOrderEventEnvelope_Event()
}

type OrderEventEnvelope_OrderPaid struct {
	// OrderPaidEvent описывает событие оплаты заказа
	OrderPaid *OrderPaidEvent `protobuf:"bytes,10,opt,name=order_paid,json=orderPaid,proto3,oneof"`
}

func (*OrderEventEnvelope_OrderPaid) isOrderEventEnvelope_Event() {}

// OrderPaidEvent описывает событие оплаты заказа
type OrderPaidEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// event_uuid идентификатор события
	EventUuid string `protobuf:"bytes,1,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`
	// order_uuid идентификатор заказа
	OrderUuid string `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	// user_uuid идентификатор пользователя
	UserUuid string `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// transaction_uuid идентификатор транзакции
	TransactionUuid string `protobuf:"bytes,4,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	// payment_method метод оплаты
	PaymentMethod v1.PaymentMethod `protobuf:"varint,5,opt,name=payment_method,json=paymentMethod,proto3,enum=common.v1.PaymentMethod" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderPaidEvent) Reset() {
	*x = OrderPaidEvent{}
	mi := &file_events_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaidEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaidEvent) ProtoMessage() {}

func (x *OrderPaidEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaidEvent.ProtoReflect.Descriptor instead.
func (*OrderPaidEvent) Descriptor() ([]byte, []int) {
	return file_events_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderPaidEvent) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *OrderPaidEvent) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *OrderPaidEvent) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *OrderPaidEvent) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

func (x *OrderPaidEvent) GetPaymentMethod() v1.PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return v1.PaymentMethod(0)
}

var File_events_order_v1_order_proto protoreflect.FileDescriptor

const file_events_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1bevents/order/v1/order.proto\x12\x0fevents.order.v1\x1a\x1ecommon/v1/payment_method.proto\"\xbe\x01\n" +
	"\x12OrderEventEnvelope\x12>\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x1f.events.order.v1.OrderEventTypeR\teventType\x12\x1d\n" +
	"\n" +
	"event_uuid\x18\x02 \x01(\tR\teventUuid\x12@\n" +
	"\n" +
	"order_paid\x18\n" +
	" \x01(\v2\x1f.events.order.v1.OrderPaidEventH\x00R\torderPaidB\a\n" +
	"\x05event\"\xd7\x01\n" +
	"\x0eOrderPaidEvent\x12\x1d\n" +
	"\n" +
	"event_uuid\x18\x01 \x01(\tR\teventUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12)\n" +
	"\x10transaction_uuid\x18\x04 \x01(\tR\x0ftransactionUuid\x12?\n" +
	"\x0epayment_method\x18\x05 \x01(\x0e2\x18.common.v1.PaymentMethodR\rpaymentMethod*M\n" +
	"\x0eOrderEventType\x12 \n" +
	"\x1cORDER_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ORDER_EVENT_TYPE_PAID\x10\x01BaZ_github.com/CantDefeatAirmanx/space-engeneering/shared/pkg/proto/events/order/v1;order_events_v1b\x06proto3"

var (
	file_events_order_v1_order_proto_rawDescOnce sync.Once
	file_events_order_v1_order_proto_rawDescData []byte
)

func file_events_order_v1_order_proto_rawDescGZIP() []byte {
	file_events_order_v1_order_proto_rawDescOnce.Do(func() {
		file_events_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_order_v1_order_proto_rawDesc), len(file_events_order_v1_order_proto_rawDesc)))
	})
	return file_events_order_v1_order_proto_rawDescData
}

var file_events_order_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_order_v1_order_proto_goTypes = []any{
	(OrderEventType)(0),        // 0: events.order.v1.OrderEventType
	(*OrderEventEnvelope)(nil), // 1: events.order.v1.OrderEventEnvelope
	(*OrderPaidEvent)(nil),     // 2: events.order.v1.OrderPaidEvent
	(v1.PaymentMethod)(0),      // 3: common.v1.PaymentMethod
}
var file_events_order_v1_order_proto_depIdxs = []int32{
	0, // 0: events.order.v1.OrderEventEnvelope.event_type:type_name -> events.order.v1.OrderEventType
	2, // 1: events.order.v1.OrderEventEnvelope.order_paid:type_name -> events.order.v1.OrderPaidEvent
	3, // 2: events.order.v1.OrderPaidEvent.payment_method:type_name -> common.v1.PaymentMethod
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_events_order_v1_order_proto_init() }
func file_events_order_v1_order_proto_init() {
	if File_events_order_v1_order_proto != nil {
		return
	}
	file_events_order_v1_order_proto_msgTypes[0].OneofWrappers = []any{
		(*OrderEventEnvelope_OrderPaid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_order_v1_order_proto_rawDesc), len(file_events_order_v1_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_order_v1_order_proto_goTypes,
		DependencyIndexes: file_events_order_v1_order_proto_depIdxs,
		EnumInfos:         file_events_order_v1_order_proto_enumTypes,
		MessageInfos:      file_events_order_v1_order_proto_msgTypes,
	}.Build()
	File_events_order_v1_order_proto = out.File
	file_events_order_v1_order_proto_goTypes = nil
	file_events_order_v1_order_proto_depIdxs = nil
}
