// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify
// Code generated for CantDefeatAirmanx service
// © CantDefeatAirmanx 2025.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentClientConfigInterface creates a new instance of MockPaymentClientConfigInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentClientConfigInterface(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockPaymentClientConfigInterface {
	mock := &MockPaymentClientConfigInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentClientConfigInterface is an autogenerated mock type for the PaymentClientConfigInterface type
type MockPaymentClientConfigInterface struct {
	mock.Mock
}

type MockPaymentClientConfigInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentClientConfigInterface) EXPECT() *MockPaymentClientConfigInterface_Expecter {
	return &MockPaymentClientConfigInterface_Expecter{mock: &_m.Mock}
}

// Url provides a mock function for the type MockPaymentClientConfigInterface
func (_mock *MockPaymentClientConfigInterface) Url() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Url")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPaymentClientConfigInterface_Url_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Url'
type MockPaymentClientConfigInterface_Url_Call struct {
	*mock.Call
}

// Url is a helper method to define mock.On call
func (_e *MockPaymentClientConfigInterface_Expecter) Url() *MockPaymentClientConfigInterface_Url_Call {
	return &MockPaymentClientConfigInterface_Url_Call{Call: _e.mock.On("Url")}
}

func (_c *MockPaymentClientConfigInterface_Url_Call) Run(run func()) *MockPaymentClientConfigInterface_Url_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentClientConfigInterface_Url_Call) Return(s string) *MockPaymentClientConfigInterface_Url_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPaymentClientConfigInterface_Url_Call) RunAndReturn(run func() string) *MockPaymentClientConfigInterface_Url_Call {
	_c.Call.Return(run)
	return _c
}
